// Write a pack's mediaSummary: what its media set contains, generated by an LLM
// over the pack's own sidecars and written back into its manifest.json.
//
//   npm run goonpack:summarise                     every pack source with sidecars
//   npm run goonpack:summarise goonpacks/elise     just that one
//   npm run goonpack:summarise goonpacks/elise 2026-08-02-baseline
//                                                  from that experiment's descriptions
//
// The pack directory then the experiment, both positional and both optional —
// the same two arguments in the same order as goonpack:build, so the pair that
// builds a pack is the pair that summarises it. Left off, the experiment is the
// stock `<stem>.md` beside each item, which is what builds too.
//
// Run it whenever the set changes — a summary is derived, never hand-written, so
// re-running it is the way to fix one that has gone stale. A pack that carries
// media must have one before it builds or imports (parsePack enforces that).
//
// This is a .ts run through tsx, like goonpack-build.ts, so it can import
// parseSidecar rather than hand-rolling a second frontmatter parser.
//
// Reads OPENROUTER_API_KEY (and LLM_URL) from the environment — the npm script
// loads .env via --env-file-if-exists. The model is the named experiment's text
// model, or the app's default companion model with no experiment; MODEL
// overrides both.
import process from 'node:process';
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseSidecar, SIDECAR_EXT } from '../src/lib/goonpacks/sidecar';
import { MEDIA_TYPES, splitName } from '../src/lib/goonpacks/media';
import { sidecarName } from '../src/inference/paths';
import { experimentById } from '../src/inference/experiments';
import { DEFAULT_MODEL } from '../src/lib/companions/companions';
import { out } from './lib/colour';

// Yellow names the pack, dim carries the steps, green is the summary that ends
// up in the manifest — the same three the describing scripts use.
const { yellow, green, dim } = out;

// Written from roadmap/INFERENCE-LIBRARY.md → The set summary, which is the
// source of truth for what a summary must carry. Neutral rather than written for
// a particular companion: one summary per set, and the persona's own prompt
// supplies the attitude to it.
//
// Captions only, not the long descriptions: a set of a couple of thousand items
// runs to millions of characters of description, and the captions already carry
// the vocabulary a summary is an inventory of.
const PROMPT = `You are given the caption of every picture and video in one media
set. Write a summary of what the set contains.

It has two jobs. Whoever reads it must be able to tell what is in the set, so they
never offer what isn't there. And they must be able to phrase a request in the words
the set actually uses, because a request built from vocabulary these captions don't
contain matches nothing however good the search is.

So enumerate the vocabulary, not the items. Cover:
- who appears, and in what proportion,
- the settings and locations,
- the garments, and the words used for them,
- the range of undress, and roughly how much of the set sits at each point of it,
- the poses and acts that appear,
- hair colours and other recurring physical descriptors,
- anything else the set holds a lot of.

Order each of these by occurance, grouped by "Lots", "many", "few", "one or two", and list the hits suitable for keyword search, don't
use synonyms for things that appear in the corpus.

Give proportions in plain terms — most, about half, a fair few, one or two. Use the
set's own words rather than synonyms for them, and never introduce a term the input
doesn't use. Never list or number individual items: someone should finish it knowing
what kind of request is answerable, not holding a catalogue to choose from.

Its length follows the set — say what is there and stop. Reply with the summary
itself.`;

// The caption of every item that would ship, in filename order — the sidecar
// found the way packContents finds it, so the summary describes the set the
// pack plays with rather than everything lying in media/.
//
// It walks the media and looks up each item's sidecar, never the other way
// round. A described corpus holds a run-stamped copy of every sidecar it has
// ever written, so walking the sidecars counts an item once per time it was
// described — weighting the summary by how often a picture was re-run, and
// making the input several times the size it should be.
//
// A sidecar that won't parse stops the run naming the file, rather than
// summarising a set with a hole in it.
function readCaptions(packDir: string, experiment?: string): string[] {
  const mediaDir = join(packDir, 'media');
  if (!existsSync(mediaDir)) return [];
  const files = readdirSync(mediaDir).sort();
  const here = new Set(files);
  const captions: string[] = [];
  for (const file of files) {
    const { stem, ext } = splitName(file);
    if (MEDIA_TYPES[ext] === undefined) continue;
    const wanted =
      experiment === undefined
        ? `${stem}.${SIDECAR_EXT}`
        : sidecarName(stem, experiment);
    if (!here.has(wanted)) continue;
    const path = join(mediaDir, wanted);
    try {
      captions.push(parseSidecar(readFileSync(path, 'utf8')).caption);
    } catch (e) {
      throw new Error(`${path}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  return captions;
}

// Which model writes the summary: MODEL overrides everything, then the
// experiment whose descriptions are being summarised — its second call is the
// one that turns a reply into prose, so it is already the choice made for this
// text — and otherwise whatever the app plays companions on. Nothing is
// hardcoded here: a summary written by a model no companion runs describes the
// set in a voice nothing else in the app uses.
function modelFor(experiment: string | undefined): string {
  const override = process.env.MODEL;
  if (override !== undefined && override !== '') return override;
  if (experiment === undefined) return DEFAULT_MODEL;
  const chosen = experimentById(experiment);
  if (chosen === undefined) {
    throw new Error(
      `No experiment called ${experiment} — see src/inference/experiments/.`,
    );
  }
  return chosen.parameters.textModel ?? chosen.parameters.model;
}

async function summarise(input: string, model: string): Promise<string> {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (apiKey === undefined || apiKey === '') {
    throw new Error('OPENROUTER_API_KEY is not set — put it in .env.');
  }
  const baseUrl = process.env.LLM_URL ?? 'https://openrouter.ai/api/v1';

  console.log(dim(`Summarising — ${model}…`));
  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
      'HTTP-Referer': 'http://localhost:8931',
      'X-Title': 'autogoon summarise-pack',
    },
    body: JSON.stringify({
      model,
      // Deterministic, so re-running the same set compares prompts and models
      // rather than sampling luck.
      temperature: 0,
      messages: [
        { role: 'system', content: PROMPT },
        { role: 'user', content: input },
      ],
    }),
  });
  if (!res.ok) {
    throw new Error(
      `Request failed: ${res.status} ${res.statusText}\n${await res.text()}`,
    );
  }
  const data = await res.json();
  const raw = data?.choices?.[0]?.message?.content;
  if (typeof raw !== 'string' || raw.trim() === '') {
    throw new Error(
      `No summary was returned:\n${JSON.stringify(data, null, 2)}`,
    );
  }
  return raw.trim();
}

// One pack source named on the command line, or every directory under
// goonpacks/ that holds a manifest.json. A named source that isn't a pack is an
// error, since the argument asked for that one by name.
function packsToSummarise(named: string | undefined): string[] {
  if (named !== undefined && named !== '') {
    if (!existsSync(join(named, 'manifest.json'))) {
      console.error(`No manifest.json in ${named}.`);
      process.exit(1);
    }
    return [resolve(named)];
  }
  const packsDir = join(
    dirname(fileURLToPath(import.meta.url)),
    '..',
    'goonpacks',
  );
  if (!existsSync(packsDir)) {
    console.error('no goonpacks/ directory — nothing to summarise.');
    process.exit(1);
  }
  return readdirSync(packsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => join(packsDir, e.name))
    .filter((dir) => existsSync(join(dir, 'manifest.json')));
}

// Summarise one pack, or say why it was passed over. Returns whether it wrote.
async function summarisePack(
  packDir: string,
  experiment: string | undefined,
  model: string,
): Promise<boolean> {
  console.log(yellow(packDir));
  const captions = readCaptions(packDir, experiment);
  if (captions.length === 0) {
    // Naming the experiment matters here: a set fully described under a
    // different one looks identical to a set nobody has described at all.
    console.log(
      dim(
        `  nothing described ${experiment === undefined ? 'by a stock sidecar' : `by ${experiment}`} in ${join(packDir, 'media')}` +
          ' — describe the media first (npm run goonpack:describe-missing).',
      ),
    );
    return false;
  }
  const input = captions.map((c, n) => `[${n + 1}] ${c}`).join('\n');
  console.log(
    dim(`${captions.length} caption(s), ${input.length} characters.`),
  );

  // Read the manifest before the paid call: packsToSummarise only checks that
  // the file exists, so a malformed one would otherwise throw after the summary
  // was billed, and a summary that isn't written is unrecoverable.
  const manifestPath = join(packDir, 'manifest.json');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  const replacing = typeof manifest.mediaSummary === 'string';

  const summary = await summarise(input, model);
  manifest.mediaSummary = summary;
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

  console.log(green(summary));
  console.log(
    dim(
      `\n${replacing ? 'Replaced' : 'Wrote'} mediaSummary in ${manifestPath}.\n`,
    ),
  );
  return true;
}

async function main() {
  const [named, experiment] = process.argv.slice(2);
  // Resolved before any pack is read, so a mistyped experiment says so straight
  // away rather than as "nothing described by …" against each pack in turn.
  let model: string;
  try {
    model = modelFor(experiment);
  } catch (e) {
    console.error(e instanceof Error ? e.message : String(e));
    process.exit(1);
  }
  const packs = packsToSummarise(named);
  let written = 0;
  let failed = 0;
  // Sequential — one request at a time stays under the rate limits, and the
  // output stays readable in order.
  // One pack's failure is caught here rather than ending the run: a bad sidecar
  // or a refused request would otherwise skip every pack after it, and the packs
  // that would have succeeded each cost a real request.
  for (const dir of packs) {
    try {
      if (await summarisePack(dir, experiment, model)) written += 1;
    } catch (e) {
      console.error(`✗ ${e instanceof Error ? e.message : String(e)}\n`);
      failed += 1;
    }
  }
  console.log(`${written} of ${packs.length} pack(s) summarised`);
  if (failed > 0) process.exit(1);
}

await main();
