// Write a pack's mediaSummary: what its media set contains, generated by an LLM
// over the pack's own sidecars and written back into its manifest.json.
//
//   npm run goonpack:summarise goonpacks/aimee
//
// Run it whenever the set changes — a summary is derived, never hand-written, so
// re-running it is the way to fix one that has gone stale. A pack that carries
// media must have one before it builds or imports (parsePack enforces that).
//
// This is a .ts run through tsx, like goonpack-build.ts, so it can import
// parseSidecar rather than hand-rolling a second frontmatter parser.
//
// Reads OPENROUTER_API_KEY (and LLM_URL) from the environment — the npm script
// loads .env via --env-file-if-exists. Override the model with MODEL.
import process from 'node:process';
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import { parseSidecar, SIDECAR_EXT } from '../src/lib/goonpacks/sidecar';

// Output colours, matching the describing scripts: yellow names the pack, dim
// carries the steps, green is the summary that ends up in the manifest.
const yellow = (s: string) =>
  process.stdout.isTTY ? `\x1b[33m${s}\x1b[0m` : s;
const green = (s: string) => (process.stdout.isTTY ? `\x1b[32m${s}\x1b[0m` : s);
const dim = (s: string) => (process.stdout.isTTY ? `\x1b[2m${s}\x1b[0m` : s);

// Written from roadmap/INFERENCE-LIBRARY.md → The set summary, which is the
// source of truth for what a summary must carry. Neutral rather than written for
// a particular companion: one summary per set, and the persona's own prompt
// supplies the attitude to it.
//
// Captions only, not the long descriptions: a set of a couple of thousand items
// runs to millions of characters of description, and the captions already carry
// the vocabulary a summary is an inventory of.
const PROMPT = `You are given the caption of every picture and video in one media
set. Write a summary of what the set contains.

It has two jobs. Whoever reads it must be able to tell what is in the set, so they
never offer what isn't there. And they must be able to phrase a request in the words
the set actually uses, because a request built from vocabulary these captions don't
contain matches nothing however good the search is.

So enumerate the vocabulary, not the items. Cover:
- who appears, and in what proportion,
- the settings and locations,
- the garments, and the words used for them,
- the range of undress, and roughly how much of the set sits at each point of it,
- the poses and acts that appear,
- hair colours and other recurring physical descriptors,
- anything else the set holds a lot of.

Give proportions in plain terms — most, about half, a fair few, one or two. Use the
set's own words rather than synonyms for them, and never introduce a term the input
doesn't use. Never list or number individual items: someone should finish it knowing
what kind of request is answerable, not holding a catalogue to choose from.

Its length follows the set — say what is there and stop. Reply with the summary
itself: prose, no headings, no bullet points, no preamble.`;

// Every sidecar's caption, in filename order. A sidecar that won't parse stops
// the run naming the file, rather than summarising a set with a hole in it.
function readCaptions(packDir: string): string[] {
  const mediaDir = join(packDir, 'media');
  if (!existsSync(mediaDir)) return [];
  const captions: string[] = [];
  for (const file of readdirSync(mediaDir).sort()) {
    if (extname(file) !== `.${SIDECAR_EXT}`) continue;
    const path = join(mediaDir, file);
    try {
      captions.push(parseSidecar(readFileSync(path, 'utf8')).caption);
    } catch (e) {
      throw new Error(`${path}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  return captions;
}

async function summarise(input: string): Promise<string> {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (apiKey === undefined || apiKey === '') {
    throw new Error('OPENROUTER_API_KEY is not set — put it in .env.');
  }
  const baseUrl = process.env.LLM_URL ?? 'https://openrouter.ai/api/v1';
  const model = process.env.MODEL ?? 'minimax/minimax-m3';

  console.log(dim(`Summarising — ${model}…`));
  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
      'HTTP-Referer': 'http://localhost:8931',
      'X-Title': 'autogoon summarise-pack',
    },
    body: JSON.stringify({
      model,
      // Deterministic, so re-running the same set compares prompts and models
      // rather than sampling luck.
      temperature: 0,
      messages: [
        { role: 'system', content: PROMPT },
        { role: 'user', content: input },
      ],
    }),
  });
  if (!res.ok) {
    throw new Error(
      `Request failed: ${res.status} ${res.statusText}\n${await res.text()}`,
    );
  }
  const data = await res.json();
  const raw = data?.choices?.[0]?.message?.content;
  if (typeof raw !== 'string' || raw.trim() === '') {
    throw new Error(
      `No summary was returned:\n${JSON.stringify(data, null, 2)}`,
    );
  }
  return raw.trim();
}

async function main() {
  const packDir = process.argv[2];
  if (packDir === undefined || packDir === '') {
    console.error('Usage: npm run goonpack:summarise <pack-source-dir>');
    process.exit(1);
  }
  const manifestPath = join(packDir, 'manifest.json');
  if (!existsSync(manifestPath)) {
    console.error(`No manifest.json in ${packDir}.`);
    process.exit(1);
  }
  console.log(yellow(packDir));

  const captions = readCaptions(packDir);
  if (captions.length === 0) {
    console.error(
      `No sidecars in ${join(packDir, 'media')} — describe the media first (npm run goonpack:describe-missing).`,
    );
    process.exit(1);
  }
  const input = captions.map((c, n) => `[${n + 1}] ${c}`).join('\n');
  console.log(
    dim(`${captions.length} caption(s), ${input.length} characters.`),
  );

  const summary = await summarise(input);
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  const replacing = typeof manifest.mediaSummary === 'string';
  manifest.mediaSummary = summary;
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

  console.log(green(summary));
  console.log(
    dim(
      `\n${replacing ? 'Replaced' : 'Wrote'} mediaSummary in ${manifestPath}.`,
    ),
  );
}

await main();
